#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

list=$(git diff-index --cached --name-only HEAD)
  for i in $list;
  do
    while read line;
    do
      if [ "$line" == "DO NOT COMMIT YET" ]
      then
        git reset -- $i
      fi
    done < "$i"
done

